### ISSUE TITLE
Can't sign in Unicornucopia

### ISSUE THREAD

**Issue by yuchien302** [cornelltech/startup-ideas#1]
Somehow after I registered a new account, signin, and signout, I can't be able to sign in anymore. Nor can I registered a new account under same NetID Email.

<img width="962" alt="2015-09-06 18 58 18" src="https://cloud.githubusercontent.com/assets/1877281/9707033/4eb918c6-54c9-11e5-99de-79c9c3f0d6fb.png">

Also, unable to find the Unicornucopia's repo, so I decided to post the Issue here instead.

**Comment by AVatch** [comment]
Hi - this is because the password you are entering does not match the password you signed up with.

**Comment by AVatch** [comment]
Please email me to reset it if you can't remember your password akv36@cornell.edu
